### ISSUE TITLE
Vulnerability: Unauthorized Access/Register to any Non IITK User

### ISSUE THREAD

**Issue by Naman-K-Jaiswal** [kartik3777/ProfInfo-Central#2]
#### Description
Currently, the website does not enforce restrictions on user authentication, allowing anyone to log in and access sensitive information and functionalities. Email authentication being not limited to IITK students and professors poses a huge security risk.

#### Vulnerability Type
- Authentication bypass

#### Steps to Reproduce
1. Visit the website.
2. Attempt to register with any non IITK / unauthorized email id.
3. Notice that unauthorized users can access these routes and view sensitive information.

Logging in using another non IITK email (unauthorized):
![image](https://github.com/kartik3777/ProfInfo-Central/assets/128512002/8f8962f4-2366-4bf5-b43f-2353d5f3edd1)
Login Successful:
![image](https://github.com/kartik3777/ProfInfo-Central/assets/128512002/2ebb12d8-880d-4988-a943-beb9c525ca31)

#### Expected Behavior
Only Authenticated users of IITK should be able to register themselves and then login for accessing further fumctionalities.

#### Actual Behavior
Any unauthenticated third party can register themselves on the platform and login to access the data and project routes.

#### Environment
- Operating System: Microsoft Windows 11 Home Single Language
- OS Version: 10.0.22631 Build 22631
- Browser: Brave [Version 1.64.116 Chromium: 123.0.6312.105]
- Software Version: 1.0 (Latest as per 06 / 04 / 2024)

#### Recommended Fix
1. Restrict email authentication to IITK students and professors only, using domain-based filtering or verification.

#### Additional Information
This security vulnerability poses a significant risk to user data and privacy. Implementing proper access controls and restricting email authentication to authorized domains are essential steps in mitigating this risk and ensuring the security of the website.

#### Labels
- [ ] security
- [ ] vulnerability

**Comment by DEEKSHITHASONTAM** [comment]
Made it authorised  so that only unauthorized users can access these routes and view sensitive information.
